display_name: BilibiliMusic
msix_version: 1.1.0.9
publisher: "O=puretech.com, S=Some-State, C=CN"
identity_name: com.mystyle.bilibili.music
logo_path: assets/icons/app_icon.png
capabilities: internetClient
languages: zh-cn
install_certificate: "false"
certificate_path: ${MSIX_CERT_PATH}
certificate_password: xxxx
signtool_options: /td SHA256