name: bilibilimusic
description: "使用B站API获取音乐数据，并播放音乐"
version: 1.0.7+7

environment:
  sdk: '>=3.4.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.5.0+1
  dio_smart_retry: ^7.0.1
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8
  flutter_color: ^2.1.0
  flutter_staggered_grid_view: ^0.7.0
  get: ^5.0.0-release-candidate-9.3.2
  qr_flutter: ^4.1.0
  path: ^1.8.3
  file: ^7.0.0
  intl: ^0.20.2 
  path_provider: ^2.1.1
  file_picker: ^10.3.3
  permission_handler: ^12.0.1
  shared_preferences: ^2.2.2
  flutter_cache_manager: ^3.3.1
  cached_network_image: ^3.3.0
  just_audio: ^0.10.5
  just_audio_background: ^0.0.1-beta.17
    # 视频播放
  media_kit: ^1.2.0                       # Primary package.
  media_kit_video: ^1.3.0                       # For video rendering.
  media_kit_libs_video: ^1.0.6                 # Native video dependencies.
  flex_color_picker: ^3.3.0
  share_handler: ^0.0.19
  flutter_smart_dialog: ^4.9.5 #各种弹窗 Toast/Dialog/Popup
  easy_refresh: ^3.4.0
  flutter_inappwebview: ^6.2.0-beta.2
  http: ^1.2.1
  marquee_list: ^1.0.0
  parallax_cards: ^1.0.2
  crypto: ^3.0.3
  screen_brightness: ^2.0.0+2
  flutter_volume_controller: ^1.2.7
  audio_video_progress_bar: ^2.0.3
  date_format: ^2.0.7
  wakelock_plus: ^1.1.3
  battery_plus: ^7.0.0
  stop_watch_timer: ^3.0.2
  flutter_exit_app: ^1.1.2
  url_launcher: ^6.1.12
  collection: ^1.18.0
  audio_service: ^0.18.17
  window_manager: ^0.5.1
  windows_single_instance: ^1.0.1
  flutter_animate: ^4.5.0
  toggle_switch: ^2.3.0
  font_awesome_flutter: ^10.7.0
  uuid: ^4.4.2
  ripple_wave: ^0.1.4
  server_nano_nano: 1.0.2
  network_info_plus: ^7.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3  # 添加插件
  msix: ^3.16.7
flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/bilibili_2.png"  # 图标路径
  adaptive_icon_background: "#FFFFFF"  # Android 适应性图标背景色
  windows:
    generate: true
    image_path: assets/images/bilibili_2.png
    icon_size: 48 # min:48, max:256, default: 48
flutter:
  uses-material-design: true
  assets:
    - assets/images/

msix_config:
  display_name: Bilibili Music
  # publisher_display_name: puretech.com
  # identity_name: com.puretech.purelive
  msix_version: 1.0.0.7
  logo_path: assets/images/bilibili_2.png
  # capabilities: internetClient
  certificate_path: assets/keystore/CERTIFICATE.pfx
  certificate_password: xxxx
