name: bilibilimusic
description: "使用B站API获取音乐数据，并播放音乐"
version: 1.0.7+7
publish_to: none
environment:
  sdk: '>=3.4.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.1
  file_picker: ^10.2.0
  audio_metadata_reader:
    git:
      url: https://github.com/GerryDush/audio_metadata_reader.git
      ref: v0.0.3
  path_provider: ^2.1.2
  provider: ^6.1.5
  media_kit: ^1.1.11
  media_kit_video: ^1.2.5
  media_kit_libs_video: ^1.0.5
  window_manager: ^0.5.1
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  bitsdojo_window: ^0.1.6
  webdav_client: ^1.2.2
  audio_service: ^0.18.18
  audio_service_win:
     git:
      url: https://github.com/GerryDush/audio_service_win.git
      ref: main
  tray_manager: ^0.5.1
  crypto: ^3.0.0
  flutter_colorpicker: ^1.1.0
  flutter_acrylic: ^1.1.4
  connectivity_plus: ^6.1.4
  shelf: ^1.4.2
  shelf_web_socket: ^3.0.0
  move_to_desktop: ^0.0.2
  screen_brightness: ^2.1.1
  drift: ^2.28.1
  drift_flutter: ^0.2.5
  sqlite3_flutter_libs: ^0.5.28
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3  # 添加插件
  msix: ^3.16.7
  build_runner: ^2.6.0
  drift_dev: ^2.28.1
flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/bilibili_2.png"  # 图标路径
  adaptive_icon_background: "#FFFFFF"  # Android 适应性图标背景色
  windows:
    generate: true
    image_path: assets/images/bilibili_2.png
    icon_size: 48 # min:48, max:256, default: 48

flutter:
  uses-material-design: true
  fonts:
    - family: SFIcons
      fonts:
        - asset: assets/fonts/sf_icons.ttf
  assets:
    - assets/images/

msix_config:
  display_name: Bilibili Music
  # publisher_display_name: puretech.com
  # identity_name: com.puretech.purelive
  msix_version: 1.0.0.7
  logo_path: assets/images/bilibili_2.png
  # capabilities: internetClient
  certificate_path: assets/keystore/CERTIFICATE.pfx
  certificate_password: xxxx
